import localFont from "next/font/local";
import Header from "./_components/Header";
import Breadcrumb from "./_components/Breadcrumb";
import "./globals.css";

const getLandingPageData = async () => {
  const version = process.env.SB_DATA_VERSION;
  const token = process.env.SB_TOKEN;
  const url = `https://api.storyblok.com/v2/cdn/stories/landing-page?version=${version}&token=${token}`;
  let req = await fetch (url, { cache: "no-store" });

  const storyData = await req.json();
  const { header_section, hero_section, grid_section } = storyData.story.content;

  return {
    header_section: header_section[0],
    hero_section: hero_section[0],
    grid_section: grid_section,
  }
}

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const storyData = await getLandingPageData();
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header data={storyData.header_section} />
        <Breadcrumb/>


        {children}
      </body>
    </html>
  );
}